# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name: "shop"
    arch: "amd64"
    system: "linux, darwin, windows"
    mod: ""
    cgo: 0

  gen:
    dao: #todo 换成你自己的密码
      - link: "mysql:root:xhw200116long3@tcp(127.0.0.1:3306)/shop"
        descriptionTag: true
        noModelComment: true